# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='City Name')),
                ('state', models.CharField(choices=[('MD', 'Maryland'), ('SD', 'South Dakota'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('PR', 'Puerto Rico'), ('TN', 'Tennessee'), ('IA', 'Iowa'), ('GU', 'Guam'), ('IL', 'Illinois'), ('NC', 'North Carolina'), ('FL', 'Florida'), ('RI', 'Rhode Island'), ('NY', 'New York'), ('NJ', 'New Jersey'), ('VT', 'Vermont'), ('WI', 'Wisconsin'), ('VI', 'Virgin Islands'), ('IN', 'Indiana'), ('NE', 'Nebraska'), ('CO', 'Colorado'), ('DE', 'Delaware'), ('OR', 'Oregon'), ('MN', 'Minnesota'), ('MI', 'Michigan'), ('MA', 'Massachusetts'), ('MP', 'Northern Mariana Islands'), ('NH', 'New Hampshire'), ('ID', 'Idaho'), ('NM', 'New Mexico'), ('PA', 'Pennsylvania'), ('AZ', 'Arizona'), ('AK', 'Alaska'), ('MT', 'Montana'), ('KY', 'Kentucky'), ('GA', 'Georgia'), ('DC', 'District of Columbia'), ('SC', 'South Carolina'), ('LA', 'Louisiana'), ('OH', 'Ohio'), ('NA', 'National'), ('NV', 'Nevada'), ('MO', 'Missouri'), ('ND', 'North Dakota'), ('MS', 'Mississippi'), ('WA', 'Washington'), ('AR', 'Arkansas'), ('HI', 'Hawaii'), ('CT', 'Connecticut'), ('CA', 'California'), ('ME', 'Maine'), ('WV', 'West Virginia'), ('AL', 'Alabama'), ('KS', 'Kansas'), ('VA', 'Virginia'), ('OK', 'Oklahoma'), ('TX', 'Texas'), ('UT', 'Utah')], max_length=2, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField()),
                ('fine_print', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, help_text='Full price', max_digits=6)),
                ('deal_price', models.DecimalField(decimal_places=2, default=0, help_text='Deal (real) Price', max_digits=6)),
                ('is_deal_active', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude (decimal)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude (decimal)')),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('mandated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_mod', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Listing')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandates', models.ManyToManyField(to='api.Mandate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=60)),
                ('zipcode', models.CharField(max_length=6)),
                ('state', models.CharField(choices=[('MD', 'Maryland'), ('SD', 'South Dakota'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('PR', 'Puerto Rico'), ('TN', 'Tennessee'), ('IA', 'Iowa'), ('GU', 'Guam'), ('IL', 'Illinois'), ('NC', 'North Carolina'), ('FL', 'Florida'), ('RI', 'Rhode Island'), ('NY', 'New York'), ('NJ', 'New Jersey'), ('VT', 'Vermont'), ('WI', 'Wisconsin'), ('VI', 'Virgin Islands'), ('IN', 'Indiana'), ('NE', 'Nebraska'), ('CO', 'Colorado'), ('DE', 'Delaware'), ('OR', 'Oregon'), ('MN', 'Minnesota'), ('MI', 'Michigan'), ('MA', 'Massachusetts'), ('MP', 'Northern Mariana Islands'), ('NH', 'New Hampshire'), ('ID', 'Idaho'), ('NM', 'New Mexico'), ('PA', 'Pennsylvania'), ('AZ', 'Arizona'), ('AK', 'Alaska'), ('MT', 'Montana'), ('KY', 'Kentucky'), ('GA', 'Georgia'), ('DC', 'District of Columbia'), ('SC', 'South Carolina'), ('LA', 'Louisiana'), ('OH', 'Ohio'), ('NA', 'National'), ('NV', 'Nevada'), ('MO', 'Missouri'), ('ND', 'North Dakota'), ('MS', 'Mississippi'), ('WA', 'Washington'), ('AR', 'Arkansas'), ('HI', 'Hawaii'), ('CT', 'Connecticut'), ('CA', 'California'), ('ME', 'Maine'), ('WV', 'West Virginia'), ('AL', 'Alabama'), ('KS', 'Kansas'), ('VA', 'Virginia'), ('OK', 'Oklahoma'), ('TX', 'Texas'), ('UT', 'Utah')], max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('contact', models.CharField(blank=True, help_text='Advertising contact', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email address of contact', max_length=254)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ListingCategory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vendor',
            field=models.ForeignKey(help_text="Deal's offer", on_delete=django.db.models.deletion.CASCADE, to='api.Vendor', verbose_name='Advertiser'),
        ),
    ]
